### ISSUE TITLE
Dockerfile build fails

### ISSUE THREAD

**Issue by dcdennis** [mmastrac/gst-omx-rpi-docker#1]
The make install has a bunch of errors, not sure what I'm missing  but I need a way to get gst-omx in a docker container on raspberry pi. 
the docker build fails when it runs '/bin/sh -c cp ./omx/.libs/libgstomx.so /usr/lib/arm-linux-gnueabi/gstreamer-1.0/'  because the directories do not exist. Creating them makes the build pass but omx plugins are not present on the container

**Comment by mmastrac** [comment]
Could you drop a log here? It's possible the rpi userland has evolved since I last built this container.

**Comment by dcdennis** [comment]
[build-log.txt](https://github.com/mmastrac/gst-omx-rpi-docker/files/4800627/build-log.txt)

Here's the output from the failed build command.  Let me know what I can assist with, I would like to find a stable build for gst-omx in docker.  I'm going to try building from an old commit to test this theory.

**Comment by dcdennis** [comment]
The same errors occurred when I attempted a build off the userland repo from July 26th, 2018 (prior to your initial Dockerfile commit).

RUN git clone https://github.com/raspberrypi/userland.git
WORKDIR "/root/userland"
RUN git checkout f74ea7fdef9911904e269127443cd8a608abeacc

**Comment by mmastrac** [comment]
Are you building on an x64 platform or on a Pi itself? I _might_ have built this container on a Pi3 but it's been a few years and is somewhat fuzzy

**Comment by mmastrac** [comment]
I see armhf in the log, so looks like it was on a Pi. Hmm. Will continue to dig in

**Comment by mmastrac** [comment]
Good news - looks like I still have the build cached on my Pi:

```
Sending build context to Docker daemon  135.2kB
Step 1/20 : FROM debian:buster
 ---> 48db7768914f
Step 2/20 : ARG FFMPEG_VERSION=4.0.2
 ---> Using cache
 ---> e9a46b28b2b3
Step 3/20 : RUN echo "Building FFMPEG (${FFMPEG_VERSION})"
 ---> Using cache
 ---> 28de55eeabf2
Step 4/20 : RUN DEBIAN_FRONTEND=noninteractive apt-get -qq update
 ---> Using cache
 ---> 15f72b2770a7
Step 5/20 : RUN DEBIAN_FRONTEND=noninteractive apt-get -y -qq install build-essential cmake cmake-data curl git libomxil-bellagio-dev libx264-dev pkg-config sudo xz-utils
 ---> Using cache
 ---> b443a5e3a64d
Step 6/20 : WORKDIR "/root"
 ---> Using cache
 ---> a5f5a78b3b1d
Step 7/20 : RUN git clone --depth 1 https://github.com/raspberrypi/userland.git
 ---> Using cache
 ---> cef1045331df
Step 8/20 : WORKDIR "/root/userland"
 ---> Using cache
 ---> 2c62fdefaa25
Step 9/20 : RUN ./buildme
 ---> Using cache
 ---> 8b22b5815fa7
Step 10/20 : RUN echo "/opt/vc/lib" > /etc/ld.so.conf.d/00-vmcs.conf
 ---> Using cache
 ---> 278cd44d3a86
Step 11/20 : RUN ldconfig
 ---> Using cache
 ---> 678c0489209b
Step 12/20 : RUN DEBIAN_FRONTEND=noninteractive apt-get -y -qq install gstreamer1.0-plugins-*
 ---> Using cache
 ---> 53d7e0656bcb
Step 13/20 : RUN DEBIAN_FRONTEND=noninteractive apt-get -y -qq install libgstreamer-plugins-base1.0-dev
 ---> Using cache
 ---> ca0c8935054e
Step 14/20 : RUN curl -o gst-omx.tar.xz https://gstreamer.freedesktop.org/src/gst-omx/gst-omx-1.14.2.tar.xz
 ---> Using cache
 ---> 1e4b790aaea6
Step 15/20 : RUN tar xf gst-omx.tar.xz
 ---> Using cache
 ---> a12cc41af71a
Step 16/20 : WORKDIR gst-omx-1.14.2
 ---> Using cache
 ---> 047612f2b859
Step 17/20 : RUN ./configure --with-omx-target=rpi CFLAGS="-I/opt/vc/include/IL -I/opt/vc/include" LDFLAGS="-L/opt/vc/lib"
 ---> Using cache
 ---> b961a94f0156
Step 18/20 : RUN make
 ---> Using cache
 ---> 6233f3f26316
Step 19/20 : RUN make install
 ---> Using cache
 ---> 35e1931b344a
Step 20/20 : RUN cp ./omx/.libs/libgstomx.so /usr/lib/arm-linux-gnueabi/gstreamer-1.0/
 ---> Using cache
 ---> e04d9f16177c
Successfully built e04d9f16177c
```

I will see what I can do to reverse engineer the layers.

**Comment by mmastrac** [comment]
The userland commit that I successfully built with previously was `f74ea7fdef9911904e269127443cd8a608abeacc`

**Comment by dcdennis** [comment]
Im building on my raspberry pi 3b+. It's interesting that the build is failing on the same userland commit that previously worked.  Have you been successful building the image again on your pi?

**Comment by mmastrac** [comment]
Aha! I dug into the final container that was failing. Can you try the following patch locally and let me know if it works?

```
--- a/Dockerfile
+++ b/Dockerfile
@@ -29,4 +29,4 @@ RUN make

 # Manual install
 RUN make install
-RUN cp ./omx/.libs/libgstomx.so /usr/lib/arm-linux-gnueabi/gstreamer-1.0/
+RUN cp ./omx/.libs/libgstomx.so /usr/lib/arm-linux-gnueabihf/gstreamer-1.0/
```

**Comment by dcdennis** [comment]
Ahh! nice find! This change got omx working in our docker container. Thanks for the help resolving the issue, I appreciate it.

Side note I was able to get the omxh264dec in an ubuntu image by installing the gstreamer1.0-omx library on the pi itself and symlinking the plugin path into the container.  I need the encoder as well but there seems to be a way to symlink the omx plugin into a docker image if you can track down all dependencies.

**Comment by mmastrac** [comment]
Great to hear. I have been wary of chasing deps down because that can be somewhat delicate. I'm assuming you're using Hypriot but I'm sure there might be alternative docker distros in the future. :)

Note that this project could be improved by using a multi-stage build to avoid having all the build deps littering the filesystem afterwards.

**Comment by mmastrac** [comment]
Committed to master and closing this one. Thanks for the help!
